name: Node.js CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
         
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 20

        - name: Install Dependencies
          run: npm install

        - name: Check ESLint binary permission (debugging)
          run: ls -l node_modules/.bin && file node_modules/.bin/eslint
  
        - name: Fix ESLint permissions
          run: chmod +x node_modules/.bin/eslint

        - name: Run Linter
          run: npx eslint .
        
        - name: Run Test
          run: npm test